version: '3'

services:
  db:
    container_name: postgres_server
    image: postgres
    environment:
      POSTGRES_DB: anepokis_db
      POSTGRES_USER: anepokis_username
      POSTGRES_PASSWORD: anepokis_password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    network_mode: host

  web:
    container_name: anepokis_server
    build: .
    environment:
      PORT: 8413
      A_DB_NAME: postgres
      A_DB_STRING: postgres://anepokis_username:anepokis_password@localhost:5432/anepokis_db?sslmode=disable
    depends_on:
      - db
    network_mode: host

volumes:
  postgres:
